# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-28 20:26
from __future__ import unicode_literals

from django.db import migrations, models
import picklefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_datetime', models.DateTimeField(auto_now=True)),
                ('display_board', picklefield.fields.PickledObjectField(editable=False)),
                ('board', picklefield.fields.PickledObjectField(editable=False)),
            ],
        ),
    ]
