# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-29 01:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20160528_2344'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_over',
            field=models.BooleanField(default=False),
        ),
    ]
