# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-29 03:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_game_game_over'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='win',
            field=models.BooleanField(default=False),
        ),
    ]
