# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-29 04:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_game_win'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='difficulty',
            field=models.IntegerField(choices=[(0, 'Super Easy'), (1, 'Easy'), (2, 'Normal'), (3, 'Hard')], default=1, null=True),
        ),
    ]
