# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-29 20:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_auto_20160529_0400'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='end_timer',
            field=models.PositiveIntegerField(default=100000),
            preserve_default=False,
        ),
    ]
