# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-29 20:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_game_end_timer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='end_timer',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
